<Project>

  <PropertyGroup>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <UseArtifactsOutput>true</UseArtifactsOutput>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Nethermind</Authors>
    <Copyright>Demerzel Solutions Limited</Copyright>
  </PropertyGroup>

</Project>
