name: Publish ZisK Docker image

on:
  workflow_call:
    inputs:
      zisk_ref:
        description: Zisk ref
        required: true
        type: string
        default: v0.17.0
  workflow_dispatch:
    inputs:
      zisk_ref:
        description: Zisk ref
        required: true
        type: string
        default: v0.17.0

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    env:
      TARGET: x86_64-unknown-linux-gnu
    outputs:
      commit_hash: ${{ steps.check_ref.outputs.commit_hash }}
      latest: ${{ steps.check_latest.outputs.latest }}
      tag: ${{ steps.check_ref.outputs.tag }}

    steps:
      - name: Check out zisk repository
        uses: actions/checkout@v6
        with:
          repository: 0xPolygonHermez/zisk
          ref: ${{ inputs.zisk_ref }}

      - name: Check repository reference
        id: check_ref
        run: |
          ref="${{ inputs.zisk_ref }}"
          tag="${ref#refs/tags/}"

          if git show-ref --verify --quiet "refs/tags/$tag"; then
            echo "tag=$tag" >> $GITHUB_OUTPUT
          fi

          echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Check for the latest release
        id: check_latest
        if: steps.check_ref.outputs.tag != ''
        uses: actions/github-script@v8
        with:
          script: |
            const ref = '${{ inputs.zisk_ref }}'.replace(/^refs\/tags\//, '');
            const { data } = await github.rest.repos.getLatestRelease({
              owner: '0xPolygonHermez',
              repo: 'zisk',
            });

            core.setOutput('latest', ref === data.tag_name);

      - name: Install Rust toolchain
        run: |
          rustup toolchain install stable --profile default
          rustup default stable
          rustup target add $TARGET

      - name: Install dependencies
        working-directory: tools/test-env
        run: ./install_deps.sh

      - name: Build
        run: cargo build --release --target $TARGET

      - name: Pack binaries
        run: |
          mkdir -p zisk-dist/bin
          cp ./target/$TARGET/release/cargo-zisk zisk-dist/bin/
          cp ./target/$TARGET/release/ziskemu zisk-dist/bin/
          cp ./target/$TARGET/release/riscv2zisk zisk-dist/bin/
          cp ./target/$TARGET/release/zisk-coordinator zisk-dist/bin/
          cp ./target/$TARGET/release/zisk-worker zisk-dist/bin/
          cp ./ziskup/ziskup zisk-dist/bin/
          cp ./target/$TARGET/release/libziskclib.a zisk-dist/bin/

          mkdir -p zisk-dist/zisk/emulator-asm/src
          cp -r ./emulator-asm/src zisk-dist/zisk/emulator-asm
          cp -r ./lib-c/ zisk-dist/zisk
          cp ./emulator-asm/Makefile zisk-dist/zisk/emulator-asm

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: cargo_zisk_linux_amd64
          path: zisk-dist
          if-no-files-found: error

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    env:
      TARGET: x86_64-unknown-linux-gnu
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Download ZisK binaries
        uses: actions/download-artifact@v8
        with:
          name: cargo_zisk_linux_amd64
          path: zisk

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Publish to Docker Hub
        run: |
          image_name=nethermindeth/zisk
          tags=(-t $image_name:${{ needs.build.outputs.commit_hash }})

          if [[ "${{ needs.build.outputs.tag }}" != "" ]]; then
            tag="${{ needs.build.outputs.tag }}"
            tags+=(-t $image_name:${tag#v})
          fi

          [[ "${{ needs.build.outputs.latest }}" == "true" ]] && tags+=(-t $image_name:latest)

          docker buildx build . -f Dockerfile.zisk "${tags[@]}" --push
